In [6]:
list1 = [1,2,3,4,5,6,7]

In [8]:
list2 = list1.copy()

In [9]:
print(list2)

[1, 2, 3, 4, 5, 6, 7, '6']


In [10]:
#made a mistake with appending... let us retry
list1.pop(7)

'6'

In [11]:
print(list1)

[1, 2, 3, 4, 5, 6, 7]


In [12]:
print(list2)

[1, 2, 3, 4, 5, 6, 7, '6']


In [14]:
list2.clear()

In [15]:
list1.count(5)

1

In [16]:
list1.index(1)

0

In [17]:
l1 = [21, 0, 3, 1, 34, 8, 13, 1, 55, 5, 2]


In [18]:
l2 = [x**2 for x in l1]

print(l2)

[441, 0, 9, 1, 1156, 64, 169, 1, 3025, 25, 4]


In [19]:
#Understanding function creation

In [20]:
""" def my_function(arg1, arg2=default2,... \
argn=defaultn):
’’’Docstring (optional) ’’’
instructions to be executed
when executing the function
return result # optional """

' def my_function(arg1, arg2=default2,... argn=defaultn):\n’’’Docstring (optional) ’’’\ninstructions to be executed\nwhen executing the function\nreturn result # optional '

In [28]:
def picard_beverage():

    """Make Captain Picard’s beverage"""

    beverage = 'Tea.'
    kind = 'Earl Grey'
    temperature = 'Hot.'
    result = beverage + kind + temperature
    return result


In [25]:
picard_beverage()

'Tea.Earl GreyHot.'

In [29]:
print(picard_beverage.__doc__)

Make Captain Picard’s beverage


In [31]:
def area_triangle(base, height):
    """We are finding the area of a triangle"""
    result = base*height/2
    return result

area_triangle(5,10)

25.0

In [33]:
print(area_triangle.__doc__)

We are finding the area of a triangle


In [34]:
def conv_temp(temp,scale):
    """We are converting temperatures from farenheit to celsius or celsius to farenheit"""
    s = 'converting {0} {1}'.format(temp,scale)
    if scale == 'C':
        print(s)
        result = (temp*9/5)+32
    elif scale == 'F':
        print(s)
        result = (temp-32) *5/9
    else:
        print('You must use C or F for scale')
    return result


In [38]:
conv_temp(451,'C')
print(conv_temp)

converting 451 C
<function conv_temp at 0x0000023CF37731F0>


In [39]:
print(conv_temp.__doc__)

We are converting temperatures from farenheit to celsius or celsius to farenheit


In [41]:
sq = lambda n:n*n

In [42]:
sq(3)

9

In [ ]:
# first way to use lambda function... notice num does not actually change it is a new list
num = [4,14,25,6]

[sq(n) for n in num]


[16, 196, 625, 36]

In [ ]:
#here we can see num our list did not actually change
print(num)

[4, 14, 25, 6]


In [ ]:
#one method of using a lambda function
num = [12,23,35,64]

num2 = []

for n in num:
    num2.append(sq(n))

print(num2)




[144, 529, 1225, 4096]


In [52]:
import math

def area_circle(radius):
    """Area of a circle with radius = radius"""
    result = radius*math.pi
    return result

area_circle(5)


15.707963267948966

In [53]:
#working with numpy, scipy and pandas
import numpy as np
list_a = [0,1,1,2,3]
list_b = [5,8,13,21,34]

#python treats these as lists, so we cannot add or multiply these values... simply concatenate them


In [54]:
list_a+list_b

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

In [55]:
A = np.array(list_a)
B = np.array(list_b)

In [56]:
type(B)

numpy.ndarray

In [57]:
C = A+B
C

array([ 5,  9, 14, 23, 37])

In [58]:
C = A*B
C

array([  0,   8,  13,  42, 102])

In [59]:
C = np.dot(A,B)

In [60]:
C

165

In [61]:
M1 = np.matrix([[5,10], [2,4]])

M2 = np.matrix([[30,60], [5,10]])


In [62]:
M3 = M1+M2

In [63]:
M3

matrix([[35, 70],
        [ 7, 14]])

In [64]:
A

array([0, 1, 1, 2, 3])

In [66]:
A.shape

(5,)

In [67]:
M1.shape

(2, 2)

In [68]:
A.dtype

dtype('int32')

In [69]:
M1.dtype

dtype('int32')

In [70]:
a = np.arange(12)
print(a[1:4]) ; print(a[0:10:2])

[1 2 3]
[0 2 4 6 8]


In [71]:
a3 = np.array([np.arange(5), 0.5*np.arange(5)])
a3

array([[0. , 1. , 2. , 3. , 4. ],
       [0. , 0.5, 1. , 1.5, 2. ]])

In [72]:
a3[1, : ]

array([0. , 0.5, 1. , 1.5, 2. ])

In [73]:
a3[2, : ]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [74]:
a3[ : , 2]

array([2., 1.])

In [75]:
#Example use of nparrays
#Grades within a school with 5 students and 3 subjects

grades = np.array([[8,9,7], 
                   [4.5,6,3.5],
                   [8.5, 10,9],
                   [8,6.5,10],
                   [7,10,6]])

In [76]:
grades

array([[ 8. ,  9. ,  7. ],
       [ 4.5,  6. ,  3.5],
       [ 8.5, 10. ,  9. ],
       [ 8. ,  6.5, 10. ],
       [ 7. , 10. ,  6. ]])

In [77]:
grades[1, : ]

array([4.5, 6. , 3.5])

In [79]:
grades [2, : ]

array([ 8.5, 10. ,  9. ])

In [80]:
grades [0, : ]

array([8., 9., 7.])

In [81]:
grades [4, : ]

array([ 7., 10.,  6.])

In [82]:
grades[2,1]

10.0

In [85]:
import scipy
from scipy import linalg

In [86]:
x = np.array([[1,10],[1,21],[1,29],[1,35]])
y = np.array([[0.9], [2.2], [3.1], [3.5]])

In [87]:
from numpy import dot

In [88]:
n = linalg.inv(dot(x.T, x))
k = dot(x.T, y)

coef = dot(n,k)

In [89]:
coef

array([[-0.0955809 ],
       [ 0.10612972]])

In [90]:
from scipy import optimize
f = lambda x: np.tan(x) - 1
optimize.fsolve(f, 0)

array([0.78539816])

In [ ]:
#some measures of central tendency
#median: The middle most value, the value for which 50% of the values fall above and below
#mode: The most common value
#arithmeticmean: The mean we all learn in school. The average of all the values. Population mean = u, sample mean = Xbar
#geometricmean: The multiplication product of all the values to the 1/n. N= sample size. Used for exponential observations like interest rates and population growth rates.
#harmonicmean:

In [92]:
from scipy import stats
stats.mode(grades)

C:\Users\david\AppData\Local\Temp\ipykernel_22320\1033413227.py:2: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  stats.mode(grades)


ModeResult(mode=array([[ 8. , 10. ,  3.5]]), count=array([[2, 2, 1]]))

In [94]:
import pandas as pd

file_path = r"C:\Users\david\Downloads\cars.csv"

cars = pd.read_csv(file_path)

cars

mpg  cyl        disp   hp      drat        wt       qsec  vs  am  \
0    19.363503    4  206.285777  272  4.280528  3.009137  21.578267   1   1   
1    33.767858    4  166.582187  177  3.411314  1.580285  15.226811   0   1   
2    28.299849    8  182.210424  101  3.740265  2.788317  18.689839   1   0   
3    24.966462    6  192.569290  132  3.054762  2.345792  18.047109   1   0   
4    13.900466    6  392.494522  299  2.876242  2.809989  18.891634   0   0   
..         ...  ...         ...  ...       ...       ...        ...  ..  ..   
145  10.922174    8   90.324413  252  2.714344  2.226391  15.373434   0   1   
146  25.239108    6  434.245769   61  3.394825  5.133802  16.178459   0   0   
147  22.566976    6  391.914395  123  3.565235  3.833567  14.147125   1   0   
148  11.286969    8  204.863972  273  2.984941  3.103406  21.314390   0   1   
149  16.966162    6  433.584336   65  3.038486  3.348023  14.942009   1   1   

     gear  carb  
0       5     4  
1       3     3  
2       5     1  
3       4     4  
4       3     1  
..    ...   ...  
145     4     4  
146     3     2  
147     3     4  
148     4     4  
149     4     3  

[150 rows x 11 columns]

In [97]:
cars.loc[:, 'mpg'].mode()

0      10.138053
1      10.173803
2      10.514612
3      10.635478
4      10.785730
         ...    
145    34.140801
146    34.239616
147    34.247746
148    34.294552
149    34.672173
Name: mpg, Length: 150, dtype: float64

In [106]:
cars['mpg'].mode()

0      10.138053
1      10.173803
2      10.514612
3      10.635478
4      10.785730
         ...    
145    34.140801
146    34.239616
147    34.247746
148    34.294552
149    34.672173
Name: mpg, Length: 150, dtype: float64

In [108]:
ct = cars.groupby(['am'])
ct['mpg'].apply(lambda x: x.mode())

am    
0   0     10.138053
    1     10.635478
    2     10.785730
    3     10.859713
    4     11.161260
            ...    
1   66    33.242441
    67    33.722138
    68    33.767858
    69    34.061182
    70    34.672173
Name: mpg, Length: 150, dtype: float64

In [111]:
np.median(grades, axis = 0)

array([8., 9., 7.])

In [112]:
cars.loc[:, 'mpg'].median()

21.202780974457966

In [113]:
ct['mpg'].median()

am
0    19.159046
1    23.068321
Name: mpg, dtype: float64

In [123]:
physics = grades[:, 0]
print('The average physics grade is', np.mean(physics))

The average physics grade is 7.2


In [124]:
grades

array([[ 8. ,  9. ,  7. ],
       [ 4.5,  6. ,  3.5],
       [ 8.5, 10. ,  9. ],
       [ 8. ,  6.5, 10. ],
       [ 7. , 10. ,  6. ]])

In [122]:
average = (8+4.5+8.5+8+7)/5
average

7.2

In [125]:
#To explain we just defined the variable physics as all of the rows within the 0th column of the array. We then found the mean.

In [126]:
np.mean(grades, axis = 0)

array([7.2, 8.3, 7.1])

In [127]:
#That gave us all the averages for all the different subjects

In [128]:
print('MPG average is', cars['mpg'].mean())

MPG average is 21.822178367487666


In [132]:
print(ct['mpg'].mean())

am
0    21.132976
1    22.589037
Name: mpg, dtype: float64


In [135]:
luh = cars.groupby(['am'])
luh['cyl'].mean()

am
0    6.101266
1    5.859155
Name: cyl, dtype: float64