In [6]:
list1 = [1,2,3,4,5,6,7]

In [8]:
list2 = list1.copy()

In [9]:
print(list2)

[1, 2, 3, 4, 5, 6, 7, '6']


In [10]:
#made a mistake with appending... let us retry
list1.pop(7)

'6'

In [11]:
print(list1)

[1, 2, 3, 4, 5, 6, 7]


In [12]:
print(list2)

[1, 2, 3, 4, 5, 6, 7, '6']


In [14]:
list2.clear()

In [15]:
list1.count(5)

1

In [16]:
list1.index(1)

0

In [17]:
l1 = [21, 0, 3, 1, 34, 8, 13, 1, 55, 5, 2]


In [18]:
l2 = [x**2 for x in l1]

print(l2)

[441, 0, 9, 1, 1156, 64, 169, 1, 3025, 25, 4]


In [19]:
#Understanding function creation

In [20]:
""" def my_function(arg1, arg2=default2,... \
argn=defaultn):
’’’Docstring (optional) ’’’
instructions to be executed
when executing the function
return result # optional """

' def my_function(arg1, arg2=default2,... argn=defaultn):\n’’’Docstring (optional) ’’’\ninstructions to be executed\nwhen executing the function\nreturn result # optional '

In [28]:
def picard_beverage():

    """Make Captain Picard’s beverage"""

    beverage = 'Tea.'
    kind = 'Earl Grey'
    temperature = 'Hot.'
    result = beverage + kind + temperature
    return result


In [25]:
picard_beverage()

'Tea.Earl GreyHot.'

In [29]:
print(picard_beverage.__doc__)

Make Captain Picard’s beverage


In [31]:
def area_triangle(base, height):
    """We are finding the area of a triangle"""
    result = base*height/2
    return result

area_triangle(5,10)

25.0

In [33]:
print(area_triangle.__doc__)

We are finding the area of a triangle


In [34]:
def conv_temp(temp,scale):
    """We are converting temperatures from farenheit to celsius or celsius to farenheit"""
    s = 'converting {0} {1}'.format(temp,scale)
    if scale == 'C':
        print(s)
        result = (temp*9/5)+32
    elif scale == 'F':
        print(s)
        result = (temp-32) *5/9
    else:
        print('You must use C or F for scale')
    return result


In [38]:
conv_temp(451,'C')
print(conv_temp)

converting 451 C
<function conv_temp at 0x0000023CF37731F0>


In [39]:
print(conv_temp.__doc__)

We are converting temperatures from farenheit to celsius or celsius to farenheit


In [41]:
sq = lambda n:n*n

In [42]:
sq(3)

9

In [ ]:
# first way to use lambda function... notice num does not actually change it is a new list
num = [4,14,25,6]

[sq(n) for n in num]


[16, 196, 625, 36]

In [ ]:
#here we can see num our list did not actually change
print(num)

[4, 14, 25, 6]


In [ ]:
#one method of using a lambda function
num = [12,23,35,64]

num2 = []

for n in num:
    num2.append(sq(n))

print(num2)




[144, 529, 1225, 4096]


In [52]:
import math

def area_circle(radius):
    """Area of a circle with radius = radius"""
    result = radius*math.pi
    return result

area_circle(5)


15.707963267948966

In [53]:
#working with numpy, scipy and pandas
import numpy as np
list_a = [0,1,1,2,3]
list_b = [5,8,13,21,34]

#python treats these as lists, so we cannot add or multiply these values... simply concatenate them


In [54]:
list_a+list_b

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

In [55]:
A = np.array(list_a)
B = np.array(list_b)

In [56]:
type(B)

numpy.ndarray

In [57]:
C = A+B
C

array([ 5,  9, 14, 23, 37])

In [58]:
C = A*B
C

array([  0,   8,  13,  42, 102])

In [59]:
C = np.dot(A,B)

In [60]:
C

165

In [61]:
M1 = np.matrix([[5,10], [2,4]])

M2 = np.matrix([[30,60], [5,10]])


In [62]:
M3 = M1+M2

In [63]:
M3

matrix([[35, 70],
        [ 7, 14]])

In [64]:
A

array([0, 1, 1, 2, 3])

In [66]:
A.shape

(5,)

In [67]:
M1.shape

(2, 2)

In [68]:
A.dtype

dtype('int32')

In [69]:
M1.dtype

dtype('int32')

In [70]:
a = np.arange(12)
print(a[1:4]) ; print(a[0:10:2])

[1 2 3]
[0 2 4 6 8]


In [71]:
a3 = np.array([np.arange(5), 0.5*np.arange(5)])
a3

array([[0. , 1. , 2. , 3. , 4. ],
       [0. , 0.5, 1. , 1.5, 2. ]])

In [72]:
a3[1, : ]

array([0. , 0.5, 1. , 1.5, 2. ])

In [73]:
a3[2, : ]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [74]:
a3[ : , 2]

array([2., 1.])

In [75]:
#Example use of nparrays
#Grades within a school with 5 students and 3 subjects

grades = np.array([[8,9,7], 
                   [4.5,6,3.5],
                   [8.5, 10,9],
                   [8,6.5,10],
                   [7,10,6]])

In [76]:
grades

array([[ 8. ,  9. ,  7. ],
       [ 4.5,  6. ,  3.5],
       [ 8.5, 10. ,  9. ],
       [ 8. ,  6.5, 10. ],
       [ 7. , 10. ,  6. ]])

In [77]:
grades[1, : ]

array([4.5, 6. , 3.5])

In [79]:
grades [2, : ]

array([ 8.5, 10. ,  9. ])

In [80]:
grades [0, : ]

array([8., 9., 7.])

In [81]:
grades [4, : ]

array([ 7., 10.,  6.])

In [82]:
grades[2,1]

10.0

In [85]:
import scipy
from scipy import linalg

In [86]:
x = np.array([[1,10],[1,21],[1,29],[1,35]])
y = np.array([[0.9], [2.2], [3.1], [3.5]])

In [87]:
from numpy import dot

In [88]:
n = linalg.inv(dot(x.T, x))
k = dot(x.T, y)

coef = dot(n,k)

In [89]:
coef

array([[-0.0955809 ],
       [ 0.10612972]])

In [90]:
from scipy import optimize
f = lambda x: np.tan(x) - 1
optimize.fsolve(f, 0)

array([0.78539816])

In [ ]:
#some measures of central tendency
#median: The middle most value, the value for which 50% of the values fall above and below
#mode: The most common value
#arithmeticmean: The mean we all learn in school. The average of all the values. Population mean = u, sample mean = Xbar
#geometricmean: The multiplication product of all the values to the 1/n. N= sample size. Used for exponential observations like interest rates and population growth rates.
#harmonicmean:

In [92]:
from scipy import stats
stats.mode(grades)

C:\Users\david\AppData\Local\Temp\ipykernel_22320\1033413227.py:2: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  stats.mode(grades)


ModeResult(mode=array([[ 8. , 10. ,  3.5]]), count=array([[2, 2, 1]]))

In [8]:
import pandas as pd

file_path = r"C:\Users\david\Downloads\cars.csv"

cars = pd.read_csv(file_path)

cars

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\david\\Downloads\\cars.csv'

In [97]:
cars.loc[:, 'mpg'].mode()

0      10.138053
1      10.173803
2      10.514612
3      10.635478
4      10.785730
         ...    
145    34.140801
146    34.239616
147    34.247746
148    34.294552
149    34.672173
Name: mpg, Length: 150, dtype: float64

In [106]:
cars['mpg'].mode()

0      10.138053
1      10.173803
2      10.514612
3      10.635478
4      10.785730
         ...    
145    34.140801
146    34.239616
147    34.247746
148    34.294552
149    34.672173
Name: mpg, Length: 150, dtype: float64

In [108]:
ct = cars.groupby(['am'])
ct['mpg'].apply(lambda x: x.mode())

am    
0   0     10.138053
    1     10.635478
    2     10.785730
    3     10.859713
    4     11.161260
            ...    
1   66    33.242441
    67    33.722138
    68    33.767858
    69    34.061182
    70    34.672173
Name: mpg, Length: 150, dtype: float64

In [111]:
np.median(grades, axis = 0)

array([8., 9., 7.])

In [112]:
cars.loc[:, 'mpg'].median()

21.202780974457966

In [113]:
ct['mpg'].median()

am
0    19.159046
1    23.068321
Name: mpg, dtype: float64

In [123]:
physics = grades[:, 0]
print('The average physics grade is', np.mean(physics))

The average physics grade is 7.2


In [124]:
grades

array([[ 8. ,  9. ,  7. ],
       [ 4.5,  6. ,  3.5],
       [ 8.5, 10. ,  9. ],
       [ 8. ,  6.5, 10. ],
       [ 7. , 10. ,  6. ]])

In [122]:
average = (8+4.5+8.5+8+7)/5
average

7.2

In [125]:
#To explain we just defined the variable physics as all of the rows within the 0th column of the array. We then found the mean.

In [126]:
np.mean(grades, axis = 0)

array([7.2, 8.3, 7.1])

In [127]:
#That gave us all the averages for all the different subjects

In [128]:
print('MPG average is', cars['mpg'].mean())

MPG average is 21.822178367487666


In [132]:
print(ct['mpg'].mean())

am
0    21.132976
1    22.589037
Name: mpg, dtype: float64


In [135]:
luh = cars.groupby(['am'])
luh['cyl'].mean()

am
0    6.101266
1    5.859155
Name: cyl, dtype: float64

In [1]:
import numpy as np
import scipy 
import pandas as pd

ModuleNotFoundError: No module named 'numpy'

In [2]:
pip install numpy matplotlib scipy pandas

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ------- -------------------------------- 2.4/12.6 MB 12.3 MB/s eta 0:00:01
   ------------------- -------------------- 6.0/12.6 MB 14.8 MB/s eta 0:00:01
   ----------------------------- ---------- 9.4/12.6 MB 15.5 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 15.2 MB/s eta 0:00:00
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   --------------- ------------------------ 3.1/8.0 MB 16.9 MB/s eta 0:00:01
   ----------------------------- ---------- 6.0/8.0 MB 14.8 MB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 14.2 MB/s eta 0:00:00
   ---------------------------------------- 0.0/44.5 MB ? eta -:--:--
   -- ------------------------------------- 2.6/44.5 MB 13.7 MB/s eta 0:00:04
   ------ ---------------

In [3]:
import numpy as np
import pandas as pd
import scipy  
import matplotlib.pyplot

In [4]:
#Chapter 4 Statistics

#Central Tendency

#Geometric Mean - Alternative mean utilized when the distribution of a sample or population is exponential in nature.

def g_mean(x):

    avglnx = np.log(x)
    return np.exp(avglnx.mean())

bsg_ages = [45,30,50,26,40]

g_mean(bsg_ages)





np.float64(37.090904350447026)

In [5]:
from scipy.stats import gmean
gmean(bsg_ages)

np.float64(37.090904350447026)

In [6]:
#Imagine we held three stocks, equally weighted in our portfolio for a year, over the year they gave us returns of 5%, 10% and a loss of 5%
stock_returns = [1.05, 1.10, .95]
gmean(stock_returns)

np.float64(1.031419164168326)

In [ ]:
#Here is an example if we had a dataframe instead of simply an array

import pandas as pd
from scipy.stats import gmean

# Example DataFrame
data = {
    "Returns": [1.05, 1.10, 0.95],
    "Other_Column": [0.8, 1.2, 1.0],
}
df = pd.DataFrame(data)

# Calculating geometric mean on the "Returns" column
geo_mean_returns = gmean(df["Returns"])
print(geo_mean_returns)


In [7]:
# we can also do it with the dataframe we have used groupby on.
#that is the formula... but we are going to deal with it later because we dont have the file downloaded to this computer
ct['mpg'].apply(gmean)

NameError: name 'ct' is not defined

In [10]:
#The harmonic mean is interesting... it essentially takes the sum of all the reciprocal values of our sample/population, finds their arithmetic mean, takes the reciprocal of the result lol, and *n
#Harmonic mean is always < Geometric mean < arithmetic mean
#Harmonic mean is specifically used for ratios and rates, lets give an example

from statistics import harmonic_mean

h_mean = harmonic_mean(bsg_ages)

print(h_mean)

35.96679987703658


In [18]:
#you could also build a function for it but why do that when a library exists :)
# We have two companies, c_1 with a P/E of 24 and c_2 with a P/E if 13.33
#annnndd no built in weighted harmonic mean function in any lib lets build out a function

def weighted_harmonic_mean(weights, values):

    weights = np.array(weights)
    values = np.array(values)

    numerator = np.sum(weights)
    denominator = np.sum(weights/values)

    WHM = numerator/denominator

    return WHM

weights = [.2, .8]
values = [24, 13.33]

result = (weighted_harmonic_mean(weights, values))
print(result)

14.630933869935058


In [22]:
#Dispersion
#We begin with basic range

physics = [7,8,8.5,6.5,9]
physics_array = np.array(physics)
print(physics_array.max())
physics_array.min()

9.0


np.float64(6.5)

In [23]:
physics_range = physics_array.max() - physics_array.min()

In [24]:
print(physics_range)

2.5


In [26]:
#built in function for range
np.ptp(physics_array)

np.float64(2.5)

In [35]:
data = {'stockvalues' : [50,75,100],
        'date': ['5/12/2002', '5/13/2002', '5/14/2002']}

df = pd.DataFrame(data)

df['date'] = pd.to_datetime(df['date'])

np.ptp(df['stockvalues'])

np.int64(50)

In [36]:

print(df)

   stockvalues       date
0           50 2002-05-12
1           75 2002-05-13
2          100 2002-05-14


In [44]:
df1 = df.loc[:,'stockvalues']
print('Stock-Value Quantile1: ', df1.quantile(0.25))

Stock-Value Quantile1:  62.5


In [27]:
#Understanding classes briefly:
class Demo:
    def __init__(self, value):
        self.value = value  # Instance attribute

    def set_value(self): # Local variable, does nothing to the instance
        
        set_value = self.value*5

        return set_value
    


physics = Demo(5)

print(physics.set_value())
    



25


In [6]:
#Generally after the init function of the class you will not need to add any parameters to the function other than self.
#Additionally for each instance of the class, as you instantiate it, you need to pass the parameters that are specific to that class object.

class Test:
    def __init__(self, difficulty, time_length):
        self.difficulty = difficulty
        self.time_length = time_length

    def grade(self):
        
        grade = self.time_length - self.difficulty*5

        return grade
    


test_1 = Test(5, 60)
test_2 = Test(3,30)

print(test_1.grade())
print(test_2.grade())

35
15


In [19]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm  # For the cumulative distribution function (N(d1) and N(d2))


class CallOption:
    def __init__(self, ttm, r, strike, spot, sigma):
        self.ttm = ttm
        self.r = r
        self.strike = strike
        self.spot = spot
        self.sigma = sigma #volatility of the underlying asset
        self.d1 = self._calculate_d1()
        self.d2 = self._calculate_d2()
        self.N_d1 = norm.cdf(self.d1)
        self.N_d2 = norm.cdf(self.d2)

    def _calculate_d1(self):
        return (np.log(self.spot / self.strike) + (self.r + 0.5 * self.sigma ** 2) * self.ttm) / (self.sigma * np.sqrt(self.ttm))
    
    def _calculate_d2(self):
        return self.d1 - self.sigma * np.sqrt(self.ttm)

    def price(self):
        price = (
            self.spot * self.N_d1
            - self.strike * np.exp(-self.r * self.ttm) * self.N_d2
        )
        return price

    

mcdonalds_call = CallOption(ttm=0.234126984, r=0.04857, strike=225, spot=224.85, sigma=0.314)

print(f'the call option price is {mcdonalds_call.price()}')


the call option price is 14.773826660589577


In [1]:
pip install QuantLib

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------- ----------------------------- 3.1/12.6 MB 26.2 MB/s eta 0:00:01
   ------------------------- -------------- 8.1/12.6 MB 20.1 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 20.2 MB/s eta 0:00:00


In [3]:
import QuantLib as ql

fixed_leg_schedule = ql.Schedule(settlement_date,
                                 ql.Date(25, 12, 2029),
                                 ql.Period(ql.Annual),
                                 calendar,
                                 ql.ModifiedFollowing,
                                 ql.ModifiedFollowing,
                                 ql.DateGeneration.Forward,
                                 False)

floating_leg_schedule = fixed_leg_schedule  # Symmetry for simplicity

# Swap parameters
fixed_rate = 0.03
nominal = 1e6
ibor_index = ql.Euribor6M(ql.YieldTermStructureHandle(yield_curve))

swap = ql.VanillaSwap(ql.VanillaSwap.Payer, nominal,
                      fixed_leg_schedule, fixed_rate, ql.Actual360(),
                      floating_leg_schedule, ibor_index, 0.0, ql.Actual360())

engine = ql.DiscountingSwapEngine(ql.YieldTermStructureHandle(yield_curve))
swap.setPricingEngine(engine)

npv = swap.NPV()
print(f"Swap NPV: {npv}")


NameError: name 'settlement_date' is not defined

In [ ]:
#alright back to basic statistics... we really should just grind this thing today

